name: 'SAST for GitHub Actions'
description: 'A GitHub Action that performs static analysis on your workflows'
inputs:
  REPO_TOKEN:
    description: 'Github token'
    required: true
  TARGET_INPUT:
    description: 'Repository name'
    required: true
  
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    - uses: actions/checkout@v3
      with:
        repository: 'magmanu/gh-workflow-auditor'
    
    - name: Install Dependencies
      run: |
        pwd
        pip install -r requirements.txt
        pip install python-dotenv
      shell: bash
    - name: Run scan
      env:
        TARGET_TYPE: "repo"
        TARGET_INPUT: ${{ github.GITHUB_REPOSITORY }}
        GITHUB_TOKEN: ${{ inputs.REPO_TOKEN }}
      run: |
        echo "${TARGET_TYPE}" >> $GITHUB_ENV
        echo "${TARGET_INPUT}" >> $GITHUB_ENV
        echo "${GITHUB_TOKEN}" >> $GITHUB_ENV
        python main.py
      shell: bash
